include: package:lint/analysis_options_package.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'

linter:
  rules:
    prefer_relative_imports: true
    avoid_relative_lib_imports: false
    unawaited_futures: true
    public_member_api_docs: true